# Generated by Django 4.0.7 on 2022-10-05 12:42

import datetime
from django.db import migrations, models
import irasusapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crmuser',
            fields=[
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=100, validators=[irasusapp.models.password_validator])),
                ('password_conformation', models.CharField(default='', max_length=100, validators=[irasusapp.models.password_validator])),
                ('last_login', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('search_users', 'Can search'), ('add', 'Can add user'), ('update', 'Can update user'), ('delete', 'Can delete user'), ('assign role', 'Can Assign role')),
            },
        ),
        migrations.CreateModel(
            name='BatteryDetail',
            fields=[
                ('model_name', models.CharField(blank=True, choices=[('igtblu', 'IGTBLU'), ('igtred', 'IGTRED'), ('igtred+', 'IGTRED+')], default='', max_length=100)),
                ('battery_serial_num', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('battery_type', models.CharField(choices=[('24', '24'), ('48', '48'), ('60', '60'), ('72', '72')], default='', max_length=100)),
                ('bms_type', models.CharField(choices=[('ion', 'ION'), ('electrifuel', 'ELECTRIFUEL')], default='', max_length=100)),
                ('iot_type', models.CharField(choices=[('tarckmate', 'TRACKMATE'), ('electrifuel', 'ELECTRIFUEL'), ('aeidth', 'AEIDTH')], default='', max_length=100)),
                ('iot_imei_number', models.CharField(max_length=100)),
                ('sim_number', models.CharField(blank=True, default='', max_length=12)),
                ('warrenty_start_date', models.DateField(blank=True, default='')),
                ('warrenty_duration', models.DateField(blank=True, default='')),
                ('assigned_owner', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in_swap_station', 'IN_SWAP_STATION'), ('in_vehicle', 'IN_VEHICLE'), ('idel', 'IDEL'), ('damaged', 'DAMAGED')], default='', max_length=50)),
                ('battery_cell_chemistry', models.CharField(default='', max_length=50)),
                ('battery_pack_nominal_voltage', models.CharField(default='', max_length=50)),
                ('battery_pack_nominal_charge_capacity', models.CharField(default='', max_length=50)),
                ('charging_status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
