# Generated by Django 4.0.7 on 2022-10-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('irasusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.organisation'),
        ),
        migrations.AddField(
            model_name='crmuser',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.role'),
        ),
    ]
