# Generated by Django 4.0.7 on 2022-10-05 12:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_pack_manufacture', models.CharField(default='', max_length=225)),
                ('battery_pack_distributor', models.CharField(default='', max_length=225)),
                ('battery_pack_sub_distributor', models.CharField(default='', max_length=100)),
                ('battery_pack_financier', models.CharField(default='', max_length=100)),
                ('battery_pack_owner', models.CharField(default='', max_length=100)),
                ('battery_pack_operator', models.CharField(default='', max_length=100)),
                ('vehical_manufacture', models.CharField(default='', max_length=100)),
                ('vehical_distributor', models.CharField(default='', max_length=100)),
                ('vehical_sub_distributor', models.CharField(default='', max_length=100)),
                ('vehical_retailer', models.CharField(default='', max_length=100)),
                ('vehical_financier', models.CharField(default='', max_length=100)),
                ('vehical_owner', models.CharField(default='', max_length=100)),
                ('vehical_operator', models.CharField(default='', max_length=100)),
                ('battrey_swap_satation_manufacture', models.CharField(default='', max_length=100)),
                ('battrey_swap_satation_distributor', models.CharField(default='', max_length=100)),
                ('battrey_swap_satation_sub_distributor', models.CharField(default='', max_length=100)),
                ('battrey_swap_satation_financier', models.CharField(default='', max_length=100)),
                ('battrey_swap_satation_owner', models.CharField(default='', max_length=100)),
                ('battrey_swap_satation_operator', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(default=1000, max_length=225)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('serial_number', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('org_users', models.ManyToManyField(related_name='org_users', to=settings.AUTH_USER_MODEL)),
                ('organisation_profile', models.ManyToManyField(to='user_management.organisationprofile')),
            ],
        ),
    ]
