# Generated by Django 4.0.7 on 2022-09-28 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irasusapp', '0005_crmuser_is_admin_alter_crmuser_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmuser',
            options={'permissions': (('search_users', 'Can search'), ('add', 'Can add user'), ('update', 'Can update user'), ('delete', 'Can delete user'), ('assign role', 'Can Assign role'))},
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 12, 8, 4, 239440)),
        ),
    ]
