# Generated by Django 4.0.7 on 2022-09-28 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irasusapp', '0006_alter_crmuser_options_alter_crmuser_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'permissions': (('search_users', 'Can search dataa'), ('add', 'Can add user'), ('update', 'Can update user'), ('delete', 'Can delete user'), ('assign role', 'Can Assign role'))},
        ),
        migrations.AlterField(
            model_name='batterydetail',
            name='iot_imei_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 13, 55, 17, 513005)),
        ),
    ]
